# Generated by Django 5.0.1 on 2024-01-12 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='اسم عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(auto_created=True, default=0, editable=False, verbose_name='تعداد لایک')),
                ('date', models.DateField(auto_created=True, auto_now_add=True, verbose_name='زمان')),
                ('titel', models.CharField(max_length=60, verbose_name='عنوان')),
                ('sub_titel', models.CharField(max_length=150, verbose_name='زیر عنوان')),
                ('text', models.TextField(verbose_name='متن اصلی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categorys', models.ManyToManyField(to='blog.categorys', verbose_name='دسته بندی')),
            ],
        ),
    ]
